### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by ClaudiuCreanga** [tzyganu/Magento2SampleModule#13]
> Don't put many hopes in this. Based on the comments on the magento 2 repo the grid system will be changed...A LOT.

Did that change happen with 2.1? Can we consider that your model here is the stable one or will be changed by magento in the near future?

Thanks!

**Comment by tzyganu** [comment]
@ClaudiuCreanga There are (at least were) a lot of changes happening weekly in the Magento 2 repo and I couldn't keep up with them.  
Most of the changes were related to the way that grids and forms act in the backend.  
The latest version of this module should be compatible with M2.1 now. I just hope there are no other big changes in the following weeks.  
I tried to follow the standards of the ui components, remove all calls to deprecated methods, remove all `load` and `save` calls from models.  
From the talks I had with the core team members, this should be the stable model for the future, but I cannot guarantee it.  
I've already tested this approach on the M2.2 - dev branch and it seams to work.  
Let's just hope for the best :smile: .
