### ISSUE TITLE
Error after installing this extension

### ISSUE THREAD

**Issue by kishanemipro** [tzyganu/Magento2SampleModule#2]
After installing this module, I am getting following error.

Setup version for module 'Sample_News' is not specified

I am using Magento ver. 0.74.0-beta11

Please let me know how to fix this. Thanks.

**Comment by tzyganu** [comment]
@kishanemipro The module is kind of old. A lot has changed in Magento 2 since I created this. I didn't get around to update this. I will try to make it compatible with the latest version soon.

**Comment by kishanemipro** [comment]
Ok. Thanks a lot.

**Comment by sebi-p** [comment]
Thank you for your work. I'm also looking forward to see the updated version.

**Comment by refaelgold** [comment]
same here!! thanks!!

**Comment by sergei-sss** [comment]
+

**Comment by tzyganu** [comment]
I've just released a new version. Let me know if this works for you. Also if you find any bugs, or inconsistencies, please report them. Thanks for the feedback.  
@kishanemipro If this works for you, please close the issue.

**Comment by refaelgold** [comment]
Thanks! i will check it!!
Great Work!!
@tzyganu any chance you have a blog or website? I really like your answer at stackoverflow. you really help me with a lot of issue at magento 1.x

**Comment by tzyganu** [comment]
@refaelgold I have a blog but I haven't written anything lately: http://marius-strajeru.blogspot.ro/

**Comment by tzyganu** [comment]
Closing this since it seams it was fixed.
