### ISSUE TITLE
Error creating new author

### ISSUE THREAD

**Issue by SLv99** [tzyganu/Magento2SampleModule#3]
Hi,

Your extension is a good base for learning to code extensions for Magento 2.0. When I try to create an author in Magento 1.0 beta I get the following message: Author Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.

I know this extension is old, but it would really help my further with my own extension too.

Thanks.

**Comment by tzyganu** [comment]
@SLv99 This sample module is outdated. I will try to come up with a new version that contains the new grid system and other improvements by the end of next week.

**Comment by SLv99** [comment]
Thanks for your reply. While developing my own extension I figured out that the problem for this extension is the Author tab (Author/Edit/Tab/Author.php), the dob field. The TimezoneInterface::FORMAT_TYPE_SHORT causes the error.

**Comment by tzyganu** [comment]
@SLv99 That's just one error. Most probably you will hit others. I'm working as we speak on fixing this. it will be available most probably next week.

**Comment by SLv99** [comment]
True, but it was the only error I came across, the rest of the extension works as far as I tested (creating author, bind it to products, show it on the frontend). It was a good base for my own extension.

Thanks.
