### ISSUE TITLE
After Installtion module not working

### ISSUE THREAD

**Issue by purvi123** [tzyganu/Magento2SampleModule#4]
Hello,

I installed module but after install i get error "Fatal error: Class 'Magento\Framework\DataObject' not found" in Sample\News\Controller\Router.php on line 115

**Comment by tzyganu** [comment]
This module is not yet compatible with the latest Magento 2 version. I'll do my best to make it compatible again.

**Comment by purvi123** [comment]
ok thanks for your reply :)

**Comment by strajeru** [comment]
@purvi123 Try again now. It should work.

**Comment by tzyganu** [comment]
@purvi123 It should work now.
